# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GravosRecycler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GravosRecycler
  platform :ios, '10.0'
  pod 'Alamofire', '~> 4.7'
  # Pods for GravosCollector
  pod 'GMStepper'
  pod 'FMDB'
  pod 'SwiftyGif'
  pod 'Parchment'
  pod 'JBDatePicker'
  pod 'JKSteppedProgressBar'
  pod 'GooglePlaces'
  pod 'GooglePlacesPicker'
  pod 'GoogleMaps'
  pod 'GooglePlacesSearchController'

  pod 'ENSwiftSideMenu', :git => 'https://github.com/evnaz/ENSwiftSideMenu.git', :tag => '0.1.3'
  target 'GravosRecyclerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
