# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GravosCollector' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '10.0'
  pod 'Alamofire', '~> 4.7'
  # Pods for GravosCollector
  pod 'GMStepper'
  pod 'SwiftyGif'
  pod 'Alamofire', '~> 4.7'
  target 'GravosCollectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
